runtime: nodejs18

env_variables:
  ASTRA_DB_APPLICATION_TOKEN: "your_astra_application_token"
  ASTRA_DB_API_ENDPOINT: "your_astra_db_api_endpoint"
  NODE_ENV: "production"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto
  secure: always
